name: "CI - Test"

on:
  push:
    branches:
      - test
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SECRETS
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Install Dependencies"
        run: npm install

      - name: "Run App (temporary)"
        env:
          PORT: ${{ secrets.PORT }}
        run: timeout -s KILL 5s node src/index.js

      - name: "Print Secret (masked)"
        run: echo "${{ secrets.PORT }}"
      - name: "upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: src
